### ISSUE TITLE
Examples may use chain nominal diameter

### ISSUE THREAD

**Issue by mattEhall** [WISDEM/RAFT#29]
Garrett pointed out the values we are using here. These look to be the nominal rather than volume-equivalent diameter for these chains. We should check all our examples and correct to volume-equivalent if needed.

https://github.com/WISDEM/RAFT/blob/7781903e8a798840eee808e97113a0fa2ce344ef/examples/VolturnUS-S_example.yaml#L1234

**Comment by shousner** [comment]
This has been corrected in this commit: https://github.com/WISDEM/RAFT/commit/b220780da593610cebd6026e9469f62232de5c51

Yes, the previous values for diameter in the RAFT designs for the VolturnUS platform were using the nominal diameter of 185mm, when it needed to use the volumetric diameter. The VolturnUS design description states that it uses R3 grade studless chain. It has been derived that for R4 grade studless chain, the volumetric diameter = 1.8 * nominal diameter. It is also shown in the manufacturer catalogs that the mass (and buoyancy) properties of chain line do not change for different grades of chain, meaning that we can multiply the nominal diameters by 1.8 to produce the correct volumetric diameter.

These changes were made in all RAFT design yamls that were based on the VolturnUS design. For the OC3 spar and OC4 semi designs, those values were already given as volumetric diameters. Their design description PDFs do not state whether that value is nominal or volumetric, but the value used in the MoorDyn file for those designs is the same as what is listed in the PDFs, meaning that we can assume it is the volumetric diameter, and we do not need to update these design yamls.
The RM1 design is also using the correct diameter.
