### ISSUE TITLE
Missing SharedMooring2.dat

### ISSUE THREAD

**Issue by rrvishnu13** [WISDEM/RAFT#39]
Hello,

Thank you for creating this excellent tool. I understand that it is possible to simulate shared mooring configuration with RAFT. 

I was trying to run the example file for a farm configuration provided here [RAFT/designs/VolturnUS-S_farm.yaml](https://github.com/WISDEM/RAFT/blob/master/designs/VolturnUS-S_farm.yaml). It comes up with the following error : 
![image](https://github.com/WISDEM/RAFT/assets/112942971/c096ba97-40e0-4551-a8a4-c6c2239ee6e8)

I could not find the file called 'SharedMooring2.dat' in the repository. Can you please help with this.

**Comment by mattEhall** [comment]
Hey Vishnu,
There are now some newer in-progress features in the master branch that we're not ready to support yet, and this is one of them. We'll get some missing files like this sorted out as soon as we get things finished. If it's really critical for your work feel free to email me and we'll see what we can do sooner!
Matt

**Comment by rrvishnu13** [comment]
Dear Matt,

Thank you very much for the reply.

Vishnu
