### ISSUE TITLE
Definitions of yaw misalignment and wind speed height in cases

### ISSUE THREAD

**Issue by LennardMVF** [WISDEM/RAFT#43]
I haven't been able to find a satisfying answer in documentation or source code regarding the attributes 'yaw_misalign' and 'wind_speed'  of each case, and just wanted to check their definitions.

For 'wind_speed' -  is this the wind speed at 10 m above mean sea level or at equilibrium hub height?

For 'yaw_misalign' - is this angle relative to the wind vector or to the overall coordinate system of the FOWT?

Many thanks

**Comment by mattEhall** [comment]
Hi Lennard,
The wind speed input would be at hub height, and the yaw misalignment would be the rotor heading relative to the wind heading.
Let us know if you encounter anything that doesn't seem to match up with those definitions.
Matt
