### ISSUE TITLE
Wrong Definition of control gains in calcAero function of Rotor.py

### ISSUE THREAD

**Issue by giannikosk** [WISDEM/RAFT#52]
I've been looking into the code of the aerodynamics calculations of raft because I am trying to understand if some results on the OC4 platform I am getting are reasonable, and I believe I've stumbled on a small error in the calcAero function of the rotor.py file. In line 872, where the torque control gains are defined, in both the integral and proportional gains, the kp_tau value is used, when it should be ki_tau for the integral term and kp_tau for the proportional term. The results I am getting after correcting this are very different from the original code (for cases where wind speed is below the rated speed).
![image](https://github.com/WISDEM/RAFT/assets/165568916/16ae4f89-e09c-4a59-9b7e-21949c8efcb5)

**Comment by mattEhall** [comment]
Thank you! This seems like quite the important correction! @lucas-carmo, could you look into this?
Matt

**Comment by lucas-carmo** [comment]
Thank you for finding this bug, @giannikosk! Do you want to open a pull request with your fix (which would formally record your contribution here on GitHub) or do you prefer that I push your fix (mentioning you) to the repo? 
Lucas

**Comment by giannikosk** [comment]
@lucas-carmo thank you I would rather you push a fixed version, I am not very familiar with git. 
Giannikos

**Comment by lucas-carmo** [comment]
Ok, thanks @giannikosk! This bug is fixed in [commit](https://github.com/WISDEM/RAFT/commit/e681975e194b685a86b8283dfcb1c035f44a1d22)
