### ISSUE TITLE
Yaw misalignment and Aerodynamic in Parked condition

### ISSUE THREAD

**Issue by IHLEE94** [WISDEM/RAFT#53]
1. I tried to check the yaw misalignment effect to the floating offshore wind turbine performance in RAFT.
   In 'Load Case' of  RAFT yaml input file, the yaw misalignment values(yaw error) in the range of 30deg to -30deg were 
   inputted. However, the results from RAFT are same in the various yaw misalignment degrees.
   I want to know whether RAFT can consider the yaw misalignment to FOWT performance or not. In RAFT, are there any special 
   input to consider the yaw misalignment effect?

2. The purpose that I use RAFT is to design of FOWT sizing with the wind load in the early stage of project. I know that RAFT has 
    the function that considers the aerodynamic load with the frequency domain analysis. Generally, FOWT sizing is carried out 
    with the parked condition (DLC6.1). Therefore, I executed the analysis for the extreme wind speed with 'aerodynamic On -no 
    control option'. In this process, it could be found that all results are same under the various wind speeds. That is, there are no
    any differences in all results between w/ wind speed and w/o wind speed. 
    I understood that RAFT can consider the aerodynamic load only in the operating condition to calculate the rotor power and 
    speed based on 'An Open-source Frequency-domain Model for Floating Wind Turbine Design Optimization' paper.
    Does RAFT consider only the aerodynamic load in the operating condition?

    If my understanding is right, are there any function or method to consider the aerodynamic load (wind load) in the parked 
   condition for FOWT design in RAFT? For example, the wind load can be calculated using the wind spectrum in RAFT.

**Comment by lucas-carmo** [comment]
Hi @IHLEE94 
Sorry, could you please elaborate on this issue a bit further?

**Comment by lucas-carmo** [comment]
Dear I.H. Lee,

Thank you for the clarification!

1. Yes, you are correct. We found a bug on the turbine yaw orientation in RAFT that was fixed in the dev branch (commit 40a48cb0bff189d877910e15378bca9a1ff63587 and a few other related commits), but we are still working on merging those fixes and other improvements into the main branch. Could you please try rerunning your cases using the dev branch?

2. Currently, RAFT does not account for the aerodynamic loads on the tower. Also, RAFT does not include the aerodynamic forcing on the rotor in the solution of body dynamics (it does include the aerodynamic forcing in the static solution), but it includes the aerodynamic damping and added mass effects introduced by the controller. We plan to address those issues in the future but it might take sometime as we are currently working on other things that are higher in our priority list.

I will let you know when those capabilities are implemented 😃

Best,
Lucas

**Comment by IHLEE94** [comment]
Thank you for your clear explanation. It's very helpful!

**Comment by IHLEE94** [comment]
Dear Sir,

I  uploaded the issues related to RAFT in GitHub.

I could not find any comments on my uploaded issues.

Considering my projects, I want to receive the prompt responses.

I think that you could  comment on those. Therefore, I send two questions which are same as GitHub issues.

The following are my issues.
============================================================================================================
I tried to use the hydrodynamic coefficient using HAMS.
I think that 'padModMaster' parameter is the selecting option of the hydrodynamic calculation method, Strip or HAMS or another.
If my understanding is right, I want to know more exact explanation of each definition values-0, 1, 2 as shown in the below.
potModMaster : 1 # [int] master switch for potMod variables; 0=keeps all member potMod vars the same, 1=turns all potMod vars to False (no HAMS), 2=turns all potMod vars to True (no strip)
What does each value mean?
============================================================================================================
I carried out the example of RAFT -VolturnUS-S.
In here, I could not check the mooring tension results.
I tried to install 'Moorpy' several times. However, I could not acquired the mooring tension.
The below is printed in the Spyder when I executed 'tempo.py' file.
Reloaded modules: moorpy.helpers, moorpy.Catenary, moorpy.nonlinear, moorpy.line, moorpy.point, moorpy.body, moorpy.lineType, moorpy.system, moorpy.MoorProps, moorpy, raft.member2pnl, raft.helpers, raft.raft_member, raft.pyIECWind, raft.raft_rotor, raft.raft_fowt, raft.raft_model, raft
Are there any installation method or Procedure? Are there something wrong?
============================================================================================================

Best Regards,

I.H. Lee
