### ISSUE TITLE
Moorpy exe 

### ISSUE THREAD

**Issue by IHLEE94** [WISDEM/RAFT#55]
I carried out the example of RAFT -VolturnUS-S.
In here, I could not check the mooring tension results.

I tried to install 'Moorpy' several times. However, I could not acquired the mooring tension.
The below is printed in the Spyder when I executed 'tempo.py' file.
Reloaded modules: moorpy.helpers, moorpy.Catenary, moorpy.nonlinear, moorpy.line, moorpy.point, moorpy.body, moorpy.lineType, moorpy.system, moorpy.MoorProps, moorpy, raft.member2pnl, raft.helpers, raft.raft_member, raft.pyIECWind, raft.raft_rotor, raft.raft_fowt, raft.raft_model, raft
Are there any installation method or Procedure? Are there something wrong?

**Comment by mattEhall** [comment]
Closing as duplicate
